### ISSUE TITLE
Clear Understanding about Api Key Encryption

### ISSUE THREAD

**Issue by phemieny7** [andrechristikan/ack-nestjs-boilerplate#311]
Firstly @andrechristikan you really did a good work with this boilerplate, But i don't understand the APi key encryption aspect, which file are we to create all the code, for the APi key encryption, because i saw some api error that relate to apiKey. i am actually using the one generated in the migration but it not working.

**Comment by andrechristikan** [comment]
In [this article](https://cloud.google.com/endpoints/docs/openapi/when-why-api-key) describe `Why and when to use API keys`
- API keys identify the calling project — the application or site — making the call to an API.
- Authentication tokens identify a user — the person — that is using the app or site.

The APi key encryption has a schema that must be allowed and a timestamp that has a tolerance in minutes (let's say 5 mins). 
That will cover
-When the APi key encryption is stolen, then that is only valid for 5 minutes.
-No one can call our endpoint, except the owner
-No one can create the ApiKey, except the owner
-Track who called the endpoint, and the controller who can call our endpoint


The Apikey is created only within migration. I do not have time to create an example (controller) for ApiKey 😅
but do not worry.. the example is already in the list of tasks.

**Comment by andrechristikan** [comment]
To use the ApiKey or this project.
You need to migrate all the init data. You can use the migration 

Run
`yarn migrate`

Then follow [this instructions](https://github.com/andrechristikan/ack-nestjs-boilerplate#api-key-encryption)

**Comment by phemieny7** [comment]
I have done everything correctly to start the application, but I don't know were the particular directory am to generate the API encryption key, and I also have run the migration

**Comment by andrechristikan** [comment]
To generate a new API Key, you can use `AuthApiService` -- `create` or `createRaw` functions.
The directory in `src/common/auth/services/auth.api.service.ts`.

E.g:
```ts
// return { _id, secret, passphrase, encryptionKey }
await this.authApiService.createRaw({
    name: 'Auth Api Key Migration',
    description: 'From migration',
    key: 'qwertyuiop12345zxcvbnmkjh',
    secret: '5124512412412asdasdasdasdasdASDASDASD',
    passphrase: 'cuwakimacojulawu',
    encryptionKey: 'opbUwdiS1FBsrDUoPgZdx',
});

// return { _id, secret, passphrase, encryptionKey }
await this.authApiService.create({
    name: 'Auth Api Key Migration',
    description: 'From migration',
});
```

If you need to create a new API key over the API, you need to create the controller layer named `ApiKeyController`.
I haven't created the controller layer yet.

**Comment by phemieny7** [comment]
After i did this 
```
@Response('auth.api.key')
    @Post('/apikey')
    async apikey(
        @Body()
        { key, secret, passphrase, encryptionKey }: AuthApiKeyCreate
    ): Promise<string> {
            const concatApiKey = `${key}:${secret}`;
            const apiKeyHashed = this.helperHashService.sha256(concatApiKey);
            const data: IAuthApiRequestHashedData = {
                key, // from 1.key
                timestamp: this.helperDateService.timestamp(), // ms timestamp
                hash: apiKeyHashed, // from 3
            }

            const apiKeyEncryption = await this.authApiService.encryptApiKey(
                data,
                encryptionKey,
                passphrase
            );

            const xApiKey = `${key}:${apiKeyEncryption}`;
            console.log(xApiKey)
            
            return xApiKey;

    }
```

I was able to generate the ApiKey but once I add it to the doc x-api-key, I do get this error in my console, 
```
    response: { statusCode: 5982, message: 'middleware.error.timestampInvalid' },
    status: 403
  },
  level: 'error',
  message: 'middleware.error.timestampInvalid',
  timestamp: '2022-10-27T12:12:52.619Z'
```

**Comment by andrechristikan** [comment]
Make sure you sent `x-timestamp` too in request headers.

The timestamp in `const data` (object data before encrypted) must be same with `x-timestamp`
